# Generated by Django 4.0.4 on 2022-07-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bloguser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
