# Generated by Django 4.0.4 on 2022-07-20 08:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='_defaults/default_user.png', upload_to=users.models.BlogUser.user_profile_images_path),
        ),
    ]
