# Generated by Django 4.0.4 on 2022-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bloguser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
