# Generated by Django 4.0.4 on 2022-07-28 11:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bloguser_first_name_bloguser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=users.models.BlogUser.user_profile_images_path),
        ),
    ]
