# Generated by Django 4.0.3 on 2022-07-31 09:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_bloguser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.BlogUser.user_profile_images_path),
        ),
    ]
