# Generated by Django 4.0.3 on 2022-08-02 17:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_bloguser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='permission_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='_defaults/default_user.png', upload_to=users.models.BlogUser.user_profile_images_path),
        ),
    ]
