# Generated by Django 4.1 on 2022-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_bloguser_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='description',
            field=models.CharField(default='Napisz coś o sobie...', max_length=200),
        ),
    ]
