# Generated by Django 4.0.3 on 2022-03-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_topic_date_created_topic_date_modified_topic_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='text',
        ),
    ]
