# Generated by Django 4.0.3 on 2022-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_topic_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
