# Generated by Django 4.0.3 on 2022-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
