# Generated by Django 4.0.3 on 2022-05-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_topic_topic_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_image',
            new_name='main_image',
        ),
    ]
