# Generated by Django 4.0.3 on 2022-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_rename_topic_image_topic_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='main_image',
            field=models.ImageField(blank=True, default='default_topic_image.png', null=True, upload_to=''),
        ),
    ]
