# Generated by Django 4.0.3 on 2022-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_topic_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='main_image',
            new_name='header_image',
        ),
    ]
