# Generated by Django 4.0.3 on 2022-06-10 09:17

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_rename_main_image_topic_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=blogapp.models.topic_images_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='header_image',
            field=models.ImageField(default='_defaults/default_topic_image.png', null=True, upload_to=''),
        ),
    ]
