# Generated by Django 4.0.3 on 2022-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_alter_topic_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='header_image',
            field=models.ImageField(default='_defaults/default_topic_image.png', null=True, upload_to=''),
        ),
    ]
