# Generated by Django 4.0.3 on 2022-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_alter_topic_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='show_in_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
