# Generated by Django 4.0.4 on 2022-07-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
